name: ftp

on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Yarn
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./todoo.nombi.info/